version: "3.7"
services:
  app:
    image: kooldev/node:14-adonis
    command:
    - adonis
    - serve
    - --dev
    ports:
    - ${KOOL_APP_PORT:-3333}:3333
    environment:
      ASUSER: ${KOOL_ASUSER:-0}
      UID: ${UID:-0}
    volumes:
    - .:/app:delegated
    networks:
    - kool_local
    - kool_global
  database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - ${KOOL_DATABASE_PORT:-3307}:3307
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD-rootpass}
      MYSQL_DATABASE: ${DB_DATABASE-database}
      MYSQL_USER: ${DB_USER-user}
      MYSQL_PASSWORD: ${DB_PASSWORD-pass}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
    - database:/var/lib/mysql:delegated
    networks:
    - kool_local
    healthcheck:
      test:
      - CMD
      - mysqladmin
      - ping
volumes:
  database: 
networks:
  kool_local: 
  kool_global:
    external: true
    name: ${KOOL_GLOBAL_NETWORK:-kool_global}
